---
- name: Instalación de Unzip
  hosts: webservers
  become: yes
  #remote_user: root
  tasks:

    - name: Install unzip package
      apt:
        name: unzip
        state: absent
        update_cache: yes
...